'use strict';

/**
 * Render a structured brief + its deck into Markdown and HTML, resolving every
 * `refs` entry to a numbered, linked source. Rendering from structure (not from
 * model markdown) keeps citations trustworthy and the movers table clean.
 */
function render(brief, deck, meta = {}) {
  const byRef = new Map(deck.items.map((d) => [d.ref, d]));
  const usedRefs = collectRefs(brief);
  const date = meta.date || deck.date;

  return { markdown: toMarkdown(brief, byRef, usedRefs, date, meta), html: toHtml(brief, byRef, usedRefs, date, meta) };
}

function collectRefs(brief) {
  const set = new Set();
  for (const h of brief.headline || []) (h.refs || []).forEach((r) => set.add(r));
  for (const s of brief.sections || []) for (const i of s.items || []) (i.refs || []).forEach((r) => set.add(r));
  for (const m of brief.movers || []) (m.refs || []).forEach((r) => set.add(r));
  return [...set].sort((a, b) => a - b);
}

const cite = (refs) => ((refs && refs.length) ? ' ' + refs.map((r) => `[${r}]`).join('') : '');

function toMarkdown(brief, byRef, usedRefs, date, meta) {
  const L = [`# Morning Brief — ${date}`, ''];
  if (meta.coverage) L.push(`_Covering ${meta.coverage}_`, '');

  L.push('## What matters most', '');
  for (const h of brief.headline || []) L.push(`- ${h.text}${cite(h.refs)}`);
  L.push('');

  for (const s of brief.sections || []) {
    if (!(s.items || []).length) continue;
    L.push(`## ${s.title}`, '');
    for (const it of s.items) {
      L.push(`### ${it.title}${cite(it.refs)}`, '', it.summary, '');
    }
  }

  if ((brief.movers || []).length) {
    L.push('## Markets — movers', '', '| Ticker | Move | Vol z | Note |', '| --- | ---: | ---: | --- |');
    for (const m of brief.movers) L.push(`| ${m.ticker} | ${fmtPct(m.pct)} | ${m.volZ} | ${m.note}${cite(m.refs)} |`);
    L.push('');
  }

  if (usedRefs.length) {
    L.push('## Sources', '');
    for (const r of usedRefs) {
      const d = byRef.get(r);
      if (!d) continue;
      L.push(`${r}. [${d.title}](${d.url}) — ${d.sourceId}`);
    }
    L.push('');
  }

  if (meta.cost != null) L.push('---', `_Generated by the ${meta.engine || 'mock'} engine · est. cost $${meta.cost.toFixed(4)}_`);
  return L.join('\n');
}

function toHtml(brief, byRef, usedRefs, date, meta) {
  const esc = (s) => String(s == null ? '' : s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
  const sup = (refs) =>
    (refs && refs.length)
      ? ' ' + refs.map((r) => `<sup><a href="#src-${r}">[${r}]</a></sup>`).join('')
      : '';
  const P = [];
  P.push(`<!doctype html><meta charset="utf-8"><title>Morning Brief — ${esc(date)}</title>`);
  P.push(
    '<style>body{font:15px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:720px;margin:24px auto;padding:0 16px;color:#1a1a1a}' +
      'h1{font-size:24px}h2{margin-top:28px;border-bottom:1px solid #eee;padding-bottom:4px}h3{margin:14px 0 4px;font-size:16px}' +
      'table{border-collapse:collapse;width:100%}th,td{border:1px solid #e3e3e3;padding:6px 8px;text-align:left;font-size:14px}' +
      'td.n{text-align:right}.up{color:#0a7d2c}.down{color:#c0392b}ol.src{font-size:13px;color:#444}sup a{text-decoration:none}</style>'
  );
  P.push(`<h1>Morning Brief — ${esc(date)}</h1>`);
  if (meta.coverage) P.push(`<p style="color:#888;font-size:13px;margin-top:-8px">Covering ${esc(meta.coverage)}</p>`);

  P.push('<h2>What matters most</h2><ul>');
  for (const h of brief.headline || []) P.push(`<li>${esc(h.text)}${sup(h.refs)}</li>`);
  P.push('</ul>');

  for (const s of brief.sections || []) {
    if (!(s.items || []).length) continue;
    P.push(`<h2>${esc(s.title)}</h2>`);
    for (const it of s.items) P.push(`<h3>${esc(it.title)}${sup(it.refs)}</h3><p>${esc(it.summary)}</p>`);
  }

  if ((brief.movers || []).length) {
    P.push('<h2>Markets — movers</h2><table><tr><th>Ticker</th><th>Move</th><th>Vol z</th><th>Note</th></tr>');
    for (const m of brief.movers) {
      const cls = m.pct >= 0 ? 'up' : 'down';
      P.push(`<tr><td>${esc(m.ticker)}</td><td class="n ${cls}">${fmtPct(m.pct)}</td><td class="n">${esc(m.volZ)}</td><td>${esc(m.note)}${sup(m.refs)}</td></tr>`);
    }
    P.push('</table>');
  }

  if (usedRefs.length) {
    P.push('<h2>Sources</h2><ol class="src">');
    for (const r of usedRefs) {
      const d = byRef.get(r);
      if (!d) continue;
      P.push(`<li id="src-${r}" value="${r}"><a href="${esc(d.url)}">${esc(d.title)}</a> — ${esc(d.sourceId)}</li>`);
    }
    P.push('</ol>');
  }
  if (meta.cost != null) P.push(`<hr><p style="color:#888;font-size:12px">Generated by the ${esc(meta.engine || 'mock')} engine · est. cost $${meta.cost.toFixed(4)}</p>`);
  return P.join('\n');
}

function fmtPct(p) {
  return `${p >= 0 ? '+' : ''}${p}%`;
}

module.exports = { render };
